Determining if the Q_WS_WIN exist failed with the following output:
Change Dir: /home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_8f9f2/fast"
/usr/bin/make -f CMakeFiles/cmTC_8f9f2.dir/build.make CMakeFiles/cmTC_8f9f2.dir/build
make[1]: Entering directory '/home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_8f9f2.dir/CheckSymbolExists.cxx.o
/usr/bin/c++    -I/usr/include/qt4   -o CMakeFiles/cmTC_8f9f2.dir/CheckSymbolExists.cxx.o -c /home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx
/home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx: In function ‘int main(int, char**)’:
/home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: error: ‘Q_WS_WIN’ was not declared in this scope
   return ((int*)(&Q_WS_WIN))[argc];
                   ^
CMakeFiles/cmTC_8f9f2.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_8f9f2.dir/CheckSymbolExists.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_8f9f2.dir/CheckSymbolExists.cxx.o] Error 1
make[1]: Leaving directory '/home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_8f9f2/fast' failed
make: *** [cmTC_8f9f2/fast] Error 2

File /home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */
#include <QtCore/qglobal.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef Q_WS_WIN
  return ((int*)(&Q_WS_WIN))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the Q_WS_QWS exist failed with the following output:
Change Dir: /home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_c48fe/fast"
/usr/bin/make -f CMakeFiles/cmTC_c48fe.dir/build.make CMakeFiles/cmTC_c48fe.dir/build
make[1]: Entering directory '/home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_c48fe.dir/CheckSymbolExists.cxx.o
/usr/bin/c++    -I/usr/include/qt4   -o CMakeFiles/cmTC_c48fe.dir/CheckSymbolExists.cxx.o -c /home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx
/home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx: In function ‘int main(int, char**)’:
/home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: error: ‘Q_WS_QWS’ was not declared in this scope
   return ((int*)(&Q_WS_QWS))[argc];
                   ^
CMakeFiles/cmTC_c48fe.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_c48fe.dir/CheckSymbolExists.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_c48fe.dir/CheckSymbolExists.cxx.o] Error 1
make[1]: Leaving directory '/home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_c48fe/fast' failed
make: *** [cmTC_c48fe/fast] Error 2

File /home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */
#include <QtCore/qglobal.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef Q_WS_QWS
  return ((int*)(&Q_WS_QWS))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the Q_WS_MAC exist failed with the following output:
Change Dir: /home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_ecaa0/fast"
/usr/bin/make -f CMakeFiles/cmTC_ecaa0.dir/build.make CMakeFiles/cmTC_ecaa0.dir/build
make[1]: Entering directory '/home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_ecaa0.dir/CheckSymbolExists.cxx.o
/usr/bin/c++    -I/usr/include/qt4   -o CMakeFiles/cmTC_ecaa0.dir/CheckSymbolExists.cxx.o -c /home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx
/home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx: In function ‘int main(int, char**)’:
/home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:8:19: error: ‘Q_WS_MAC’ was not declared in this scope
   return ((int*)(&Q_WS_MAC))[argc];
                   ^
CMakeFiles/cmTC_ecaa0.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_ecaa0.dir/CheckSymbolExists.cxx.o' failed
make[1]: *** [CMakeFiles/cmTC_ecaa0.dir/CheckSymbolExists.cxx.o] Error 1
make[1]: Leaving directory '/home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_ecaa0/fast' failed
make: *** [cmTC_ecaa0/fast] Error 2

File /home/tryan/voice_analytics/pyside/PySide-1.2.4/pyside_build/py3.5-qt4.8.7-64bit-release/shiboken/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */
#include <QtCore/qglobal.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef Q_WS_MAC
  return ((int*)(&Q_WS_MAC))[argc];
#else
  (void)argc;
  return 0;
#endif
}

